const {chromium}=require('playwright'),fs=require('node:fs'),http=require('node:http'),path=require('node:path'),assert=require('node:assert/strict');
const dir=path.resolve(__dirname,'..'),defaults=require('../assets/settings.js').defaults;
(async()=>{
 let saved={...defaults,display_name:'Recruiter',revision:0},failSave=false,conflict=false,holdSave=false,releaseSave,report=null,deletions=0,notificationRead=false;
 const server=http.createServer(async(req,res)=>{
  if(req.url.startsWith('/rpc/')){let raw='';for await(const chunk of req)raw+=chunk;const body=JSON.parse(raw||'{}');res.setHeader('Content-Type','application/json');const send=(value,status=200)=>{res.statusCode=status;res.end(JSON.stringify(value));};
   if(req.url==='/rpc/settings')return send(saved);
   if(req.url==='/rpc/save'){if(failSave)return send({message:'Offline'},503);if(conflict)return send({message:'Conflict',code:'PT409'},409);const update=()=>{saved={...body.settings,revision:saved.revision+1};send(saved);};if(holdSave){releaseSave=update;return;}return update();}
   if(req.url==='/rpc/report'){report={id:body.id,subject:body.subject,description:body.description,status:'open',created_at:'2026-09-15T02:00:00Z'};return send(report.id);}
   if(req.url==='/rpc/reports')return send(report?[report]:[]);
   if(req.url==='/rpc/notifications')return send([{id:'notice',kind:'assessments',message:'An assessment is ready to review · QA',job_id:'active',candidate_id:'amy',created_at:'2026-09-15T02:00:00Z',read_at:notificationRead?'2026-09-15':null}]);
   if(req.url==='/rpc/read'){notificationRead=true;return send(null);}
   if(req.url==='/rpc/delete'){deletions++;return send({status:'pending'});}
  }
  const requestPath=req.url.split('?')[0];if(requestPath!=='/'&&requestPath!=='/index.html'&&!requestPath.startsWith('/assets/')){res.statusCode=404;res.end();return;}
  const file=path.join(dir,requestPath==='/'?'index.html':requestPath);res.setHeader('Content-Type',file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':'text/html');try{res.end(fs.readFileSync(file));}catch{res.statusCode=404;res.end();}
 }).listen(0,'127.0.0.1');
 let browser;const errors=[];
 try{
  browser=await chromium.launch({headless:true,executablePath:process.env.TEST_CHROME});const context=await browser.newContext({viewport:{width:1440,height:1100},acceptDownloads:true}),page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
  await page.route('https://**',r=>r.abort());
  await page.route('**/assets/auth.js*',r=>r.fulfill({contentType:'application/javascript',body:"document.body.classList.remove('rf-auth-pending');document.body.classList.add('rf-authenticated');document.getElementById('authGate').style.display='none';"}));
  await page.route('**/assets/data.js*',r=>r.fulfill({contentType:'application/javascript',body:''}));
  await page.addInitScript(()=>{
   const rpc=async(name,body)=>{const r=await fetch('/rpc/'+name,{method:'POST',body:JSON.stringify(body||{})});const data=await r.json();if(!r.ok)throw Object.assign(Error(data.message),{code:data.code});return data;};
   const candidates=[{id:'zed',jobId:'active',name:'Zed',short:'Zed',role:'QA',managerScore:8,originalManagerScore:8,jdScore:8,resumeJDScore:8,createdAt:2},{id:'amy',jobId:'active',name:'Amy',short:'Amy',role:'QA',managerScore:5,originalManagerScore:5,jdScore:5,resumeJDScore:5,createdAt:1}].map(c=>({...c,stage:'Sourced',strengths:[],concerns:[],tags:[],screeningQuestions:[],signal:'Synthetic evidence',confidence:'Medium',rec:'Consider'}));
   const jobs=[{id:'active',title:'QA',description:'Testing',status:'active',criteria:[],weights:[],knockouts:[]},{id:'closed',title:'Closed job',description:'Closed testing',status:'closed',criteria:[],weights:[],knockouts:[]}];
   const service={load:async()=>({jobs,candidates,feedback:[],interviewOutcomes:[]}),loadSettings:()=>rpc('settings'),saveSettings:(settings,revision)=>rpc('save',{settings,revision}),loadNotifications:()=>rpc('notifications'),markNotificationsRead:ids=>rpc('read',{ids}),loadSupportRequests:()=>rpc('reports'),submitSupportRequest:(id,subject,description)=>rpc('report',{id,subject,description}),loadPersonalUsage:async()=>({jobs:2,candidates:2,ai_completed:4}),exportAccountData:async()=>({format:'ancalagon-account-export',jobs,documents:[{file_name:'Synthetic.txt',storage_path:'workspace/job/candidate/source.txt',mime_type:'text/plain'}]}),downloadResume:async()=>new Blob(['Synthetic original']),deleteAccount:()=>rpc('delete'),loadHome:async()=>null,visitHome:async()=>{},saveHome:async()=>{},loadHomeReviews:async()=>[],loadTutorial:async()=>({state:null,revision:0}),saveTutorial:async(_,revision)=>({revision:revision+1}),loadJobReassessments:async()=>[],loadCriteriaTask:async()=>null,trackEvent:async()=>{},schedule:()=>{},flush:async()=>{},loadAdminAnalytics:async()=>{throw Error('Not admin');}};
   window.AncalagonData={create:()=>service};window.ancalagonAuth={session:{user:{id:'user',email:'example@example.test',user_metadata:{display_name:'Old name'}}},workspace:{id:'workspace',name:'My workspace'}};
   window.ancalagonSupabase={auth:{signOut:async()=>{window.testSignedOut=true;window.dispatchEvent(new CustomEvent('ancalagon:auth-cleared'));return {};}}};
  });
  const settings=async()=>{await page.locator('[data-goto="backend"]').first().click();await page.locator('#settingsName:enabled').waitFor();};
  await page.goto('http://127.0.0.1:'+server.address().port+'/');await page.locator('#page-home.active').waitFor();await settings();
  assert.equal(await page.locator('#notificationDrawer').getAttribute('open'),null);assert.equal(await page.locator('#notificationList').isVisible(),false);
  const zones=await page.locator('#settingsTimeZone option').evaluateAll(options=>options.map(o=>o.value));for(const zone of ['America/New_York','America/Chicago','America/Denver','America/Phoenix','America/Los_Angeles','America/Anchorage','America/Adak','Pacific/Honolulu','America/Puerto_Rico','Pacific/Guam','Pacific/Pago_Pago','UTC'])assert.ok(zones.includes(zone),zone);
  await page.locator('#settingsName').fill('Erik <script>');await page.locator('#settingsCompany').fill('Example Talent');await page.locator('#settingsJobTitle').fill('Recruiter');await page.locator('#settingsTimeZone').selectOption('America/New_York',{force:true});await page.locator('#settingsStartPage').selectOption('jobs',{force:true});await page.locator('#settingsCandidateSort').selectOption('name',{force:true});await page.locator('#settingsShowClosed').check();await page.locator('#settingsTextSize').selectOption('larger',{force:true});await page.locator('#settingsDensity').selectOption('compact',{force:true});await page.locator('#settingsReduceMotion').check();
  failSave=true;await page.locator('#settingsSave').click();await page.getByText('Settings did not save. Your edits are still here; try Save again.',{exact:true}).waitFor();assert.equal(await page.locator('#settingsCompany').inputValue(),'Example Talent');assert.equal(await page.locator('#rf-app').getAttribute('data-text-size'),'standard');
  failSave=false;await page.locator('#settingsSave').click();await page.getByText('Your preferences are saved.',{exact:true}).waitFor();assert.equal(saved.time_zone,'America/New_York');assert.equal(await page.locator('#rf-app').getAttribute('data-text-size'),'larger');assert.equal(await page.locator('#rf-app').getAttribute('data-reduce-motion'),'true');
  await page.reload();await page.locator('#page-jobs.active').waitFor();assert.equal(await page.locator('[data-open-job="closed"]').count()>0,true);await settings();assert.equal(await page.locator('#settingsCompany').inputValue(),'Example Talent');assert.equal(await page.locator('#adminToolsNav').isVisible(),false);
  await page.locator('#notificationShortcut').click();await page.locator('[data-notification="notice"]').click();await page.locator('#page-detail.active').waitFor();assert.equal(await page.locator('#detailName').textContent(),'Amy');
  await page.locator('#backCandidates').click();assert.match(await page.locator('#candidateCards .rf-candidate').first().textContent(),/Amy/);await page.locator('#candidateSort').selectOption('manager',{force:true});assert.match(await page.locator('#candidateCards .rf-candidate').first().textContent(),/Zed/);
  await settings();await page.locator('#notificationShortcut').click();await page.waitForFunction(()=>document.querySelectorAll('#notificationList [data-notification]').length===0);await page.locator('#toggleNotificationHistory').click();assert.equal(await page.locator('[data-notification="notice"]').count(),1);await page.locator('#toggleNotificationHistory').click();assert.equal(await page.locator('[data-notification="notice"]').count(),0);
  conflict=true;await page.locator('#settingsCompany').fill('Stale edit');await page.locator('#settingsSave').click();await page.getByText('Settings changed in another tab. Your edits are still here. Reload saved settings to continue.',{exact:true}).waitFor();assert.equal(await page.locator('#settingsSave').isDisabled(),true);conflict=false;await page.locator('#settingsReload').click();await page.locator('#confirmAccept').click();await page.waitForFunction(()=>document.getElementById('settingsCompany').value==='Example Talent');
  await page.getByText('Report a problem',{exact:true}).click();await page.locator('#supportSubject').fill('Upload question');await page.locator('#supportDescription').fill('My synthetic upload needs help.');await page.locator('#supportSubmit').click();await page.waitForFunction(()=>document.getElementById('supportStatus').textContent.includes('received'));assert.equal(report.subject,'Upload question');
  const [records]=await Promise.all([page.waitForEvent('download'),page.locator('#exportAccountData').click()]);assert.equal(JSON.parse(fs.readFileSync(await records.path(),'utf8')).format,'ancalagon-account-export');const [resume]=await Promise.all([page.waitForEvent('download'),page.locator('#exportDocuments button').click()]);assert.equal(fs.readFileSync(await resume.path(),'utf8'),'Synthetic original');
  await page.locator('#settingsQuickGuides').click();await page.locator('#page-learn.active').waitFor();assert.equal(await page.locator('#at-quick-answers details').first().getAttribute('open')!==null,true);await settings();await page.locator('#settingsRestartTutorial').click();await page.locator('#confirmAccept').click();await page.locator('#at-job-form').waitFor({state:'visible'});
  await settings();await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true,'Large settings fit mobile: '+JSON.stringify(await page.evaluate(()=>[...document.querySelectorAll('#rf-app *')].filter(e=>e.getBoundingClientRect().right>innerWidth+1&&getComputedStyle(e).position!=='fixed').slice(0,10).map(e=>({id:e.id,tag:e.tagName,cls:e.className,width:e.getBoundingClientRect().width,right:e.getBoundingClientRect().right})))));await page.setViewportSize({width:1440,height:1100});
  await page.getByText('Delete account',{exact:true}).click();await page.locator('#deleteAccountPassword').fill('synthetic-password');await page.locator('#deleteAccountConfirmation').fill('DELETE');await page.locator('#deleteAccountSubmit').click();assert.equal(await page.locator('#confirmCancel').evaluate(el=>el===document.activeElement),true);await page.keyboard.press('Escape');assert.equal(deletions,0);
  // A pending settings response must not restore private profile information after sign-out.
  holdSave=true;await page.locator('#settingsCompany').fill('Private late response');await page.locator('#settingsSave').click();const deadline=Date.now()+2000;while(!releaseSave&&Date.now()<deadline)await new Promise(r=>setTimeout(r,10));assert.ok(releaseSave);await page.evaluate(()=>window.dispatchEvent(new CustomEvent('ancalagon:auth-cleared')));releaseSave();await page.waitForTimeout(100);assert.equal(await page.locator('#settingsName').inputValue(),'');assert.equal(await page.locator('#exportDocuments button').count(),0);assert.deepEqual(errors,[]);
  await context.close();console.log('Settings journey passed: saved defaults, failed saves, conflicts, sorting, notifications, support, export, tutorial, mobile accessibility, deletion cancellation, and cleared late responses.');
 }finally{if(browser)await browser.close();server.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
