(() => {
  if (!location.pathname.startsWith('/app')) return;
  const clone=x=>JSON.parse(JSON.stringify(x));
  localStorage.setItem('ancalagon-theme-v1','light');
  const description='Application Security Engineer\n\nImplement SAST and DAST testing in CI/CD pipelines. Partner with developers to triage findings and verify remediation. Perform secure design reviews for web applications and APIs. Apply OWASP guidance to identify and reduce application risk. Communicate practical security recommendations to technical and business teams.';
  const items=[
    ['Hands-on SAST and DAST implementation','The role owns testing within delivery pipelines.','Which tools did you personally configure and integrate?','Implement SAST and DAST testing in CI/CD pipelines.'],
    ['Remediation with developers','Finding issues is only useful when teams can resolve them.','How did you verify that a fix closed the vulnerability?','Partner with developers to triage findings and verify remediation.'],
    ['Web and API security reviews','The work includes design reviews across applications and APIs.','Walk me through an API design risk you identified.','Perform secure design reviews for web applications and APIs.'],
    ['Applied OWASP knowledge','The description calls for using OWASP guidance in practical work.','How have you applied OWASP guidance to a real finding?','Apply OWASP guidance to identify and reduce application risk.'],
    ['Clear security communication','Recommendations must be useful to technical and business teams.','How did you explain a security trade-off to a nontechnical team?','Communicate practical security recommendations to technical and business teams.']
  ].map(([title,reason,question,source_quote],i)=>({id:'priority-'+(i+1),title,reason,question,source_quote,requirement_type:'inferred'}));
  const profiles=[
    {name:'Maya Brooks',role:'Application Security Engineer',score:8.6,signal:'Built security testing into delivery pipelines and verified fixes.',tags:['SAST','DAST','API security'],quotes:['Integrated Semgrep SAST and OWASP ZAP DAST into CI/CD pipelines across twelve application repositories.','Partnered with developers to remediate injection vulnerabilities and verified fixes through retesting.','Reviewed REST API designs for authentication and authorization risks.'],claims:['Implemented SAST and DAST in CI/CD.','Verified vulnerability fixes with developers.','Reviewed API authentication and authorization.'],concerns:['Confirm experience communicating risk to business stakeholders.']},
    {name:'Alex Morgan',role:'Application Security Engineer',score:8.3,signal:'Broad AppSec testing and developer remediation experience.',tags:['SAST','DAST','OWASP'],quotes:['Supported SAST and DAST scanning in delivery pipelines and triaged findings with development teams.','Applied OWASP guidance to prioritize application vulnerabilities and coordinate remediation.','Presented security findings and remediation options to engineering teams.'],claims:['Supported SAST and DAST testing.','Triaged OWASP application risks.','Communicated remediation options to engineers.'],concerns:['Confirm personal ownership of scanner configuration and CI/CD integration.']},
    {name:'Taylor Reed',role:'Security Engineer',score:7.9,signal:'Strong web testing and secure design; pipeline ownership needs review.',tags:['Web security','Threat modeling','DAST'],quotes:['Performed authenticated DAST testing and manual validation of web application vulnerabilities.','Facilitated threat modeling workshops for web applications and APIs.','Worked with developers to reproduce security findings and validate remediation.'],claims:['Performed DAST and manual validation.','Facilitated application threat modeling.','Validated fixes with development teams.'],concerns:['SAST implementation is not established in the resume.']}
  ];
  for(const p of profiles)p.resume=[p.name,p.role,'Fictional profile for the blumr product demonstration.','','EXPERIENCE','Application Security Team | 2022–2026',...p.quotes.map(q=>'• '+q),'','CORE SKILLS',p.tags.join(' · ')].join('\n');
  window.demo={description,items,profiles,state:{jobs:[],candidates:[],feedback:[],interviewOutcomes:[]},docs:{},tasks:{},reassessments:[],accepted:false,lessons:[]};
  const d=window.demo;
  const snapshot=()=>({basis:'job_description',review_status:d.accepted?'accepted':'suggested',items});
  const findings=p=>items.map((item,i)=>({priority_id:item.id,status:i===4?'partial':'supported',reason:i===0?p.quotes[0]:i===1?p.quotes[1]:i===2?p.quotes[2]:i===3?'The resume describes applying security practices to application risk.':'Technical communication is supported; business stakeholder experience needs verification.',source_ids:i===4?['resume-3']:['resume-'+Math.min(i+1,3)],question:i===4?item.question:''}));
  const brief=p=>({name:p.name,role:p.role,score:p.score,manager_score:p.score,primary_signal:p.signal,jd_reason:'Assessment based on documented role-relevant experience. Open questions remain.',manager_reason:'Provisional role alignment; no direct manager calibration yet.',concerns:p.concerns,tags:p.tags,screening_questions:[items[0].question,items[4].question],resume_evidence:p.quotes.map((quote,i)=>({claim:p.claims[i],quote})),hiring_priorities:snapshot(),priority_assessment:findings(p),criteria_assessment:[{criterion:'SAST and DAST implementation',status:p.name==='Alex Morgan'?'partial':'supported',evidence_type:p.name==='Alex Morgan'?'inferred':'direct',confidence:p.name==='Alex Morgan'?'medium':'high',confidence_score:p.name==='Alex Morgan'?65:85,confidence_basis:'Source-backed evidence support; not a probability of hiring success.',reason:p.name==='Alex Morgan'?'Scanner triage indicates adjacent delivery experience; implementation ownership is not established.':p.quotes[0],inference_basis:p.name==='Alex Morgan'?'Supporting scans and triaging findings may transfer to testing delivery workflows; it does not prove personal tool implementation.':'',verification_question:'Which tools did you personally configure and integrate?',evidence:[{kind:'resume',quote:p.quotes[0]}]}],evidence_summary:{total:1,direct:p.name==='Alex Morgan'?0:1,inferred:p.name==='Alex Morgan'?1:0,unknown:0,contradicted:0},feedback_impact:{effect:'initial',summary:'Initial assessment against the job description and shared priorities.'},model:'demo-illustration'});
  const makeTask=id=>{
    const c=d.state.candidates.find(c=>c.id===id);if(!c)return;
    const p=profiles.find(p=>d.docs[id]?.startsWith(p.name));if(!p)return;
    const neutral={...c,role:'',signal:'',tags:[],strengths:[],concerns:[],resumeJDScore:0,resumeIntake:null};
    const signature=window.AncalagonContext.signature(window.AncalagonContext.build(d.state.jobs[0],neutral,[],[]));
    d.tasks[id]={candidate_id:id,job_id:c.jobId,status:'ready',revision:'demo-intake',result:{...brief(p),context_signature:signature}};
  };
  function reassess(id){
    const c=d.state.candidates.find(c=>c.id===id);if(!c||c.name!=='Alex Morgan'||!d.state.feedback.length)return;
    d.reassessments=[{job_id:c.jobId,candidate_id:id,revision:'demo-feedback',status:'ready',reason:'New manager feedback',result:{manager_score:7.2,jd_score:7.2,confidence:'medium',summary:'Feedback clarifies that Alex triaged scanner output but did not configure the tools or integrate them into CI/CD.',jd_reason:'Hands-on implementation is less supported than the original resume wording suggested.',manager_reason:'The clarified ownership gap reduces alignment with the role’s implementation responsibilities.',evidence_ids:[],evidence_support:[],questions:['Which parts of the SAST or DAST setup did you personally own?'],criteria_assessment:[],feedback_impact:{effect:'contradiction',summary:'New evidence separates using scanner results from implementing the tooling. The proposed score changes from 8.3 to 7.2.'},applied_lessons:[],learning_suggestions:[{kind:'evaluation_method',text:'Distinguish reviewing SAST/DAST findings from personally configuring and integrating the tools.',source_ids:[]}],hiring_priorities:snapshot(),priority_assessment:items.map((item,i)=>({priority_id:item.id,status:i===0?'partial':i===4?'partial':'supported',reason:i===0?'Manager feedback confirms findings triage, but no personal ownership of tool setup or pipeline integration.':i===4?'Technical communication is supported; business stakeholder experience remains unverified.':'The existing resume evidence remains relevant to this priority.',source_ids:[],question:i===0?items[0].question:i===4?items[4].question:''}))}}];
  }
  // Emulate the backend's new revision when job priorities change during intake.
  function syncTask(id){
    const task=d.tasks[id];if(!task?.result||!d.contexts?.[id])return task;
    const signature=window.AncalagonContext.signature(d.contexts[id]);
    if(task.result.context_signature!==signature){task.result.context_signature=signature;task.revision='demo-intake-'+signature;}
    return task;
  }
  const api={
    load:async()=>clone(d.state),schedule:(s,_e,status)=>{d.state=clone(s);status('saved');},flush:async s=>{if(s)d.state=clone(s);},
    loadSettings:async()=>({display_name:'Demo workspace',start_page:'home'}),loadHome:async()=>null,visitHome:async()=>{},saveHome:async()=>{},loadHomeReviews:async()=>[],loadGuidance:async()=>({enabled:false,tips:{}}),loadTutorial:async()=>({dismissed:true,completed:true,revision:1}),saveGuidance:async()=>({enabled:false,tips:{}}),trackEvent:async()=>{},loadAdminAnalytics:async()=>{throw Error('Not admin');},
    loadAssessmentLessons:async()=>clone(d.lessons),
    loadAutomaticKnowledge:async()=>[{job_id:d.state.jobs[0]?.id,items:[{rule_key:'demo-ownership',text:'Distinguish using scanner findings from personally implementing security tools.',question:'Which parts of the setup did you personally own?',supporting_candidates:4,supporting_jobs:2}]}],loadInferenceQuality:async()=>null,isAppAdmin:async()=>false,
    loadCriteriaTask:async()=>{const j=d.state.jobs[0];if(!j?.description)return null;return{job_id:j.id,revision:'demo-jd',status:'ready',input:{title:j.title,description:j.description,criteria:[]},result:{criteria:[]},priority_version:d.accepted?2:1,priority_suggestions:{title:j.title,description:j.description,items},priority_review:d.accepted?{title:j.title,description:j.description,items,review_status:'accepted'}:null};},
    reviewHiringPriorities:async()=>{d.accepted=true;},requestHiringPriorities:async()=>{},
    uploadResume:async(c,file,text)=>{d.docs[c.id]=text;},loadResumeText:async c=>d.docs[c.id]||'',
    requestResumeIntake:async id=>{if(!d.tasks[id]){d.tasks[id]={candidate_id:id,job_id:d.state.jobs[0]?.id,status:'processing',revision:'demo-intake'};setTimeout(()=>makeTask(id),850);}},
    loadResumeIntake:async id=>clone(syncTask(id)||null),loadResumeIntakes:async ids=>ids.map(syncTask).filter(Boolean).map(({result,...t})=>clone(t)),
    reviewResumeIntake:async(id,rev,state)=>{const c=state.candidates.find(c=>c.id===id),b=d.tasks[id].result;c.resumeIntake.reviewedAt=Date.now();c.managerScore=b.manager_score;c.originalManagerScore=b.manager_score;c.jdScore=b.score;c.resumeJDScore=b.score;c.aiReview={source:'resume_intake',verdict:'Needs Adjustment',correctedScore:b.manager_score,correctedJDScore:b.score,notes:b.manager_reason,createdAt:Date.now()};d.tasks[id].status='approved';d.state=clone(state);},
    loadJobReassessments:async()=>clone(d.reassessments),requestCandidateReassessment:async id=>reassess(id),
    reviewJobReassessment:async(id,rev,decision,state)=>{const c=state.candidates.find(c=>c.id===id),task=d.reassessments.find(t=>t.candidate_id===id);if(decision==='approve'){c.aiReview={source:'hybrid_reevaluation',verdict:'Needs Adjustment',correctedScore:task.result.manager_score,correctedJDScore:task.result.jd_score,notes:task.result.summary,assessment:task.result,createdAt:Date.now()};c.managerScore=task.result.manager_score;c.jdScore=task.result.jd_score;task.status='approved';}else task.status='ignored';d.state=clone(state);},
    saveAssessmentLesson:async(id,revision,index,scope)=>{d.lessons=[{id:'demo-lesson',job_id:d.state.jobs[0]?.id,kind:'evaluation_method',scope,role_key:'application security engineer',text:d.reassessments[0].result.learning_suggestions[0].text,active:true,revision:1,updated_at:new Date().toISOString()}];d.reassessments[0].result.learning_suggestions=[];}
  };
  window.AncalagonData={create:()=>api};
  window.ancalagonAuth={session:{user:{id:'fictional-demo-user'},access_token:'local-demo'},workspace:{id:'fictional-demo-workspace'}};
  Object.defineProperty(navigator,'clipboard',{value:{writeText:async text=>{d.copied=text;}}});
})();
